[tool.poetry]
name = "pos"
version = "0.1.0"
description = "description"
authors = ["Your Name <you@example.com>"]
license = "no"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
