# Generated by Django 5.1.1 on 2024-09-30 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0004_salesitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='quantity',
        ),
    ]
